---

listen_address: 127.0.0.1
listen_port: 9091
# Valid levels: trace, debug, info, warn
log_level: info
probe_path: /probe
default_timeout: 10

services:
  - name: gcp
    url: https://status.cloud.google.com/en/feed.atom
    interval: 300
  - name: genesys-cloud
    url: https://status.mypurecloud.com/history.atom
    interval: 300
