---

listen_address: 127.0.0.1
listen_port: 9091
# Valid levels: trace, debug, info, warn
log_level: info

services:
  - name: gcp
    url: https://status.cloud.google.com/en/feed.atom
    interval: 300
  - name: genesys-cloud
    url: https://status.mypurecloud.com/history.atom
    interval: 300
  - name: azure
    url: https://azurestatuscdn.azureedge.net/en-gb/status/feed
    interval: 300
  - name: cloudflare
    url: https://www.cloudflarestatus.com/history.atom
    interval: 300
  - name: openai
    url: https://status.openai.com/history.atom
    interval: 300
  - name: okta
    url: https://feeds.feedburner.com/OktaTrustRSS
    interval: 300
  # Example AWS feeds (also added automatically with the -aws flag)
  - name: aws_apigateway_eu-central-1
    url: https://status.aws.amazon.com/rss/apigateway-eu-central-1.rss
    interval: 300
  - name: aws_connect_eu-west-2
    url: https://status.aws.amazon.com/rss/connect-eu-west-2.rss
    interval: 300
  - name: aws_athena_us-west-2
    url: https://status.aws.amazon.com/rss/athena-us-west-2.rss
    interval: 300
